apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: keepalived-installer
  labels:
    {{- include "kubelived.labels" . | nindent 4 }}
    {{- with .Values.installer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "kubelived.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.installer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "kubelived.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kubelived.serviceAccountName" . }}
      hostNetwork: {{ .Values.installer.hostNetwork }}
      nodeSelector:
        {{- toYaml .Values.installer.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.installer.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.installer.tolerations | nindent 8 }}
      containers:
      - name: installer
        securityContext:
          privileged: true
        image: {{ .Values.installer.image.repository }}:{{ .Values.installer.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.installer.image.pullPolicy }}
        args: ["sleep", "24h"]
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "./scripts/install.sh"]
          preStop:
            exec:
              command: ["/bin/sh", "-c", "./scripts/uninstall.sh"]
        volumeMounts:
        - name: manifest
          mountPath: /etc/kubernetes/manifests
        - name: config
          mountPath: {{ .Values.keepalived.config_path }}
        - name: keepalived-manifest
          mountPath: /opt/kube-keepalived.yaml
          subPath: kube-keepalived.yaml
        - name: keepalived-config
          mountPath: /opt/{{ .Values.keepalived.config_file }}
          subPath: {{ .Values.keepalived.config_file }}
        - name: keepalived-scripts
          mountPath: /scripts
      volumes:
      - name: manifest
        hostPath:
          path: /etc/kubernetes/manifests
      - name: config
        hostPath:
          path: {{ .Values.keepalived.config_path }}
          type: DirectoryOrCreate
      - name: keepalived-manifest
        configMap:
          name: keepalived-manifest
      - name: keepalived-config
        configMap:
          name: keepalived-config
      - name: keepalived-scripts
        configMap:
          name: keepalived-scripts
          defaultMode: 0700