#!/bin/sh

PRIORITY=$(ifconfig eth0| grep 'inet '| awk '{print $2}'| cut -d. -f4)
KEEPALIVED_PRIORITY=${KEEPALIVED_PRIORITY:-$PRIORITY}

echo $(date) $0: "filling keepalived config file"
sed -i "s|{{ KEEPALIVED_INTERFACE }}|$KEEPALIVED_INTERFACE|g" $1
sed -i "s|{{ KEEPALIVED_STATE }}|$KEEPALIVED_STATE|g" $1
sed -i "s|{{ KEEPALIVED_PASSWORD }}|$KEEPALIVED_PASSWORD|g" $1
sed -i "s|{{ KEEPALIVED_HEALTH_SERVICE_NAME }}|$KEEPALIVED_HEALTH_SERVICE_NAME|g" $1
sed -i "s|{{ KEEPALIVED_HEALTH_SERVICE_INTERVAL }}|$KEEPALIVED_HEALTH_SERVICE_INTERVAL|g" $1
sed -i "s|{{ KEEPALIVED_HEALTH_SERVICE_TIMEOUT }}|$KEEPALIVED_HEALTH_SERVICE_TIMEOUT|g" $1
sed -i "s|{{ KEEPALIVED_HEALTH_SERVICE_CHECK }}|$KEEPALIVED_HEALTH_SERVICE_CHECK|g" $1
sed -i "s|{{ KEEPALIVED_HEALTH_SERVICE_RISE }}|$KEEPALIVED_HEALTH_SERVICE_RISE|g" $1
sed -i "s|{{ KEEPALIVED_HEALTH_SERVICE_FALL }}|$KEEPALIVED_HEALTH_SERVICE_FALL|g" $1
sed -i "s|{{ KEEPALIVED_HEALTH_SERVICE_USER }}|$KEEPALIVED_HEALTH_SERVICE_USER|g" $1
sed -i "s|{{ KEEPALIVED_ROUTER_ID }}|$KEEPALIVED_ROUTER_ID|g" $1
sed -i "s|{{ KEEPALIVED_VIRTUAL_IP }}|$KEEPALIVED_VIRTUAL_IP|g" $1
sed -i "s|{{ KEEPALIVED_PRIORITY }}|$KEEPALIVED_PRIORITY|g" $1
sed -i "s|{{ KEEPALIVED_ADVERT_INT }}|$KEEPALIVED_ADVERT_INT|g" $1

if [ ! -z "$KEEPALIVED_UNICAST_PEER" ]; then
   echo $(date) $0: "enabling unicast"
   for i in ${KEEPALIVED_UNICAST_PEER}; do
       sed -i "s|{{ KEEPALIVED_UNICAST_PEER }}|${i}\n    {{ KEEPALIVED_UNICAST_PEER }}|g" $1;
   done
   sed -i "/{{ KEEPALIVED_UNICAST_PEER }}/d" $1
else
   echo $(date) $0: "using multicast"
   sed -i "/#unicast/,/#unicast/d" $1
fi
